# Generated by Django 4.1.4 on 2023-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
