# Generated by Django 4.1.5 on 2023-01-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="recipient",
            new_name="receiver",
        ),
    ]
