# Generated by Django 4.1.5 on 2023-01-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_feedback_receiver"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
