# Generated by Django 4.1.5 on 2023-01-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_feedbackmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
