# Generated by Django 4.1.5 on 2023-01-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cv",
            field=models.FileField(null=True, upload_to="docs/"),
        ),
    ]
