# Generated by Django 4.1.4 on 2023-01-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("createresume", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="degree",
            new_name="projects",
        ),
    ]
