# Generated by Django 4.1.4 on 2023-01-12 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("createresume", "0003_resume_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="resume",
            name="projects",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="resume",
            name="work",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
